replicas: 1

image:
  name: dotjson/ion-dispatcher
  tag: latest
  pullPolicy: Always

resources:
  requests:
    cpu: 100m
    memory: 50Mi
  # limits:
  #   cpu: 100m
  #   memory: 100Mi

terminationGracePeriodSeconds: 10
nodeSelector: {}
tolerations: []
# E.g. kubernetes   ---  https://kubernetes.io/docs/concepts/configuration/assign-pod-     node/#taints-and-tolerations-beta-feature
# - key: "key1"
#   operator: "Equal"
#   value: "value1"
#   effect: "NoSchedule"
# - key: "key1"
#   operator: "Equal"
#   value: "value1"
#   effect: "NoExecute"

module:
  type: pyex
  image:
    name: dotjson/ion-python-example-module
    tag: latest
    pullPolicy: Always
  eventsPublished: ""

log:
  level: info
  sensitive: false

# Only Azure is supported at the moment
cloud:
  azure:
    clientId: ""
    clientSecret: ""
    tenantId: ""
    subscriptionId: ""
    resourceGroup: ""

blob:
  provider: azure
  azure:
    accountName: ""
    accountKey: ""
    useProxy: false

storage:
  provider: mongodb
  mongodb:
    # A comma separated list of hosts with their ports
    uri: localhost:27017
    username: ""
    password: ""

amqp:
  # Azure servicebus is the only supported at the moment
  provider: servicebus
  servicebus:
    namespace: ""

sidecar:
  port: 8080
  printConfig: false
  image:
    name: dotjson/ion-sidecar
    tag: latest
    pullPolicy: Always


job:
  maxRunningTimeMins: 10
  retryCount: 5
  subscribesToEvent: ""
