language: go

go:
  - "1.10.x"
  - "1.9.x"
  - tip

before_install:
  # Setup dependency management tool
  - curl -L -s https://github.com/golang/dep/releases/download/v0.3.1/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
  # Remove checked in vendor dir to keep us honest
  - rm -r ./vendor
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter --install

install:
  - dep ensure --vendor-only

script: 
  - go test -race -v ./...
  - gometalinter ./...
