language: go

go:
  - "1.10.x"
  - "1.9.x"
  - tip

before_install:
  # Setup dependency management tool
  - curl -L -s https://github.com/golang/dep/releases/download/v0.3.1/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter --install

install:
  - cd ./dispatcher && dep ensure -v && cd ..
  - cd ./sidecar && dep ensure -v && cd ..

script: 
  - go test -race -v ./...
  - gometalinter --vendor --disable-all --enable=errcheck --enable=vet --enable=gofmt --enable=golint --enable=deadcode --enable=varcheck --enable=structcheck ./...
