apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  labels:
    app: {{ .Values.deployment.labels }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.deployment.labels }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.labels }}
    spec:
      containers:
      - name: {{ .Values.dispatcher.name }}
        image: {{ .Values.dispatcher.image }}
        tag: {{ .Values.dispatcher.tag }}
        args: [
            "--clientid={{ .Values.azure.clientID }}",
            "--clientsecret={{ .Values.azure.clientSecret }}",
            "--tenantid={{ .Values.azure.tenantID }}",
            "--subscriptionid={{ .Values.azure.subscriptionID }}",
            "--job=true",
            "--job.maxrunningtimemins={{ .Values.job.maxRunningTimeMins }}",
            "--job.retrycount={{ .Values.job.retryCount }}",
            "--job.sidecarimage={{ .Values.sidecar.image }}",
            "--job.workerimage={{ .Values.module.image }}",
            "--loglevel={{ .Values.logs.level }}",
            "--logsensitiveconfig={{ .Values.logs.sensitive }}",
            "--resourcegroup={{ .Values.azure.resourceGroup }}",
            "--modulename={{ .Values.module.name }}",
            "--sidecar=true",
            "--sidecar.serverport={{ .Values.sidecar.port }}",
            "--sidecar.azureblobprovider=true",
            "--sidecar.azureblobprovider.blobaccountname={{ .Values.azure.blob.accountName }}",
            "--sidecar.azureblobprovider.blobaccountkey={{ .Values.azure.blob.accountKey }}",
            "--sidecar.azureblobprovider.useproxy={{ .Values.azure.blob.useProxy }}",
            "--sidecar.mongodbmetaprovider=true",
            "--sidecar.mongodbmetaprovider.name={{ .Values.mongodb.name }}",
            "--sidecar.mongodbmetaprovider.password={{ .Values.mongodb.password }}",
            "--sidecar.mongodbmetaprovider.collection={{ .Values.mongodb.collection }}",
            "--sidecar.mongodbmetaprovider.port={{ .Values.mongodb.port }}",
            "--servicebusnamespace={{ .Values.servicebus.namespace }}",
            "--eventspublished={{ .Values.module.eventsPublised }}",
            "--subscribestoevent={{ .Values.job.subscribesToEvent }}",
            "--sidecar.printconfig={{ .Values.sidecar.printConfig }}" ]

