apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    application: {{ template "fullname" . }}
    component: {{ template "name" . }}
type: Opaque
data:
{{- if .Values.cloud.azure }}
  azureClientId: {{ .Values.cloud.azure.clientId | b64enc }}
  azureClientSecret: {{ .Values.cloud.azure.clientSecret | b64enc }}
  azureTenantId: {{ .Values.cloud.azure.tenantId | b64enc }}
  azureSubscriptionId: {{ .Values.cloud.azure.subscriptionId | b64enc }}
{{- end }}
{{- if eq .Values.blob.provider "azure" }}
  blobAzureAccountName: {{ .Values.blob.azure.accountName | b64enc }}
  blobAzureAccountKey: {{ .Values.blob.azure.accountKey | b64enc }}
{{- end }}
{{- if eq .Values.storage.provider "mongodb" }}
  storageMongodbUsername: {{ .Values.storage.mongodb.username | b64enc }}
  storageMongodbPassword: {{ .Values.storage.mongodb.password | b64enc }}
{{- end }}
